"""
metadata_utils.py: Utility functions for generating metadata strings.

Author: Nathan Lima
Date: 11/17/2025
Version: 1.0
Description: Provides functions to generate metadata strings with script execution timestamp.

Usage:
    Import this module in your Python scripts to use the get_script_metadata function.

"""

import os
import datetime


def get_script_metadata():
    """
    Generate metadata string with script execution timestamp.
    Gets the name of the calling script, not this utility script.

    Returns:
        str: Formatted timestamp string
    """
    # Try to get the calling script name using inspect module
    try:
        import inspect

        # Get the caller's frame (f_back) instead of current frame
        caller_frame = inspect.currentframe().f_back
        script_name = os.path.basename(inspect.getmodule(caller_frame).__file__)
    except (NameError, AttributeError, TypeError):
        # If inspect method fails, try __file__ approach from caller
        try:
            import inspect

            # Try to get caller's globals
            caller_frame = inspect.currentframe().f_back
            caller_globals = caller_frame.f_globals
            if "__file__" in caller_globals:
                script_name = os.path.basename(caller_globals["__file__"])
            else:
                script_name = "unknown_script_name"
        except (NameError, AttributeError, TypeError):
            # Final fallback
            script_name = "unknown_script_name"

    timestamp = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    return f"Generated by: {script_name} | Date: {timestamp}"
